### ISSUE TITLE
Error posting file

### ISSUE THREAD

**Issue by justcookin** [ajwhite/slackify#4]
Hi, 

When trying to upload a file I get the following error:
```
/usr/local/lib/node_modules/slackify/lib/fileReader.js:25
  return _path2.default.isAbsolute(filename) ? filename : _path2.default.join(
                        ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at normalizeFilename (/usr/local/lib/node_modules/slackify/lib/fileReader.js:25:25)
    at readFile (/usr/local/lib/node_modules/slackify/lib/fileReader.js:29:32)
    at fileReader (/usr/local/lib/node_modules/slackify/lib/cli.js:73:35)
    at getInputSource (/usr/local/lib/node_modules/slackify/lib/cli.js:69:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/slackify/lib/cli.js:87:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Has this something to do with npm and node versions?

**Comment by atticoos** [comment]
Certainly sounds like it @justcookin, what version are you running?

Although, it looks like this was added quite some time ago, https://github.com/nodejs/node-v0.x-archive/commit/e71b90d0fa31a53890ab60ed9576150d1f22435b (April 2013)
